/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c8bdee962730f724ddc498b739bbbca7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <m17/encoder.h>
// pydoc.h is automatically generated in the build directory
#include <encoder_pydoc.h>

void bind_encoder(py::module& m)
{

    using encoder    = ::gr::m17::encoder;


    py::class_<encoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<encoder>>(m, "encoder", D(encoder))

        .def(py::init(&encoder::make),
           py::arg("source_address"),
           py::arg("destination_address"),
           D(encoder,make)
        )
        




        
        .def("set_destination",&encoder::set_destination,       
            py::arg("dest_addr"),
            D(encoder,set_destination)
        )


        
        .def("set_source",&encoder::set_source,       
            py::arg("source_addr"),
            D(encoder,set_source)
        )

        ;




}








